version: '2'
services:
    ma-app:
        image: ma
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ma-postgresql:5432/ma
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://ma-elasticsearch:9200
        ports:
            - 8080:8080
    ma-postgresql:
        extends:
            file: postgresql.yml
            service: ma-postgresql
    ma-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ma-elasticsearch
