version: '2'
services:
    multimedia_annotator-app:
        image: multimedia_annotator
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://multimedia_annotator-postgresql:5432/multimedia_annotator
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://multimedia_annotator-elasticsearch:9200
        ports:
            - 8080:8080
    multimedia_annotator-postgresql:
        extends:
            file: postgresql.yml
            service: multimedia_annotator-postgresql
    multimedia_annotator-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: multimedia_annotator-elasticsearch
