version: '2'
services:
    multimedia_annotator-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/multimedia_annotator/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=multimedia_annotator
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
